# Gradle Properties
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
loader_version=0.15.11
# Mod Properties
mod_id=holdeasyplace
mod_name=Hold Easy Place
description=A Litematica addon, to Hold easy place
archives_base_name=holdeasyplace
maven_group=com.shane
mod_version=0.1.6
# mod_url
mod_sources=https://github.com/shane04111/Hold-Easy-Place
mod_homepage=https://modrinth.com/mod/hold-easy-place
